[MainServer]
port = 12345
SYSTEM_TYPE=ARDUINO_UNO
;SYSTEM_TYPE=ARDUINO_WIFI
;SYSTEM_TYPE=WINDOWED_APPLICATIONS

[DBserver]
hostName = localhost
hostPort = 3306
hostUser = root
hostPass = 
hostDB = demo_db
